version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2_app
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2_worker
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - rabbitmq
    command: >
      /bin/sh -c "composer install --no-interaction && php yii queue-worker/listen"

volumes:
  db_data: 